### ISSUE TITLE
vsock: it doesn't work with crosvm

### ISSUE THREAD

**Issue by ikicha** [rust-vmm/vhost-device#408]
crosvm expects there are 3 queues: rx, tx, event. but vhost-user-vsock declares only 2 vqs, and it causes the problem in crosvm.

even qemu, it looks like they uses 3 queues: https://github.com/qemu/qemu/blob/6cb2011fedf8c4e7b66b4a3abd6b42c1bae99ce6/include/hw/virtio/vhost-vsock-common.h#L33

**Comment by ikicha** [comment]
and https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html#x1-4380002

**Comment by stefano-garzarella** [comment]
a vhost-user device is not a complete offload of a virtio device (as vDPA is), so it is fine that a vhost-user device handles only a subset of the queues.

For vsock, we are doing like for the vhost-vsock in-kernel device, and we handle only TX and RX, since QEMU for example is handling the event VQ: https://github.com/qemu/qemu/blob/6cb2011fedf8c4e7b66b4a3abd6b42c1bae99ce6/hw/virtio/vhost-vsock-common.c#L259

Can you describe better the issue with crosvm?
