### ISSUE TITLE
[vsock] Questions about queue size

### ISSUE THREAD

**Issue by ikicha** [rust-vmm/vhost-device#458]
For now, the queue size for vsock is 256, is it determined in the spec, or arbitrary value?

I assume vhost-user frontend can send `VHOST_USER_SET_VRING_NUM` with any value below max queue size, and it means back-end should handle every valid value, is it right assumption? (and there is no API to query backend's queue size from frontend)

From the assumption, some vmm(crosvm) sends VHOST_USER_SET_VRING_NUM with maximum value(32768). So I was just curious if we can increase the queue size if there is no regression in QEMU.

**Comment by stefano-garzarella** [comment]
> For now, the queue size for vsock is 256, is it determined in the spec, or arbitrary value?

It is an arbitrary value and since it is used in `vhost-user-backend` to allocate resources, it makes sense to keep a reasonable value.

> 
> I assume vhost-user frontend can send `VHOST_USER_SET_VRING_NUM` with any value below max queue size, 

Yep, this assumption is right.

> and it means back-end should handle every valid value, is it right assumption? 

Nope, the device can refuse if the value is too large and it can't handle that size.
Maybe we need to clarify that into the vhost-user spec.

> (and there is no API to query backend's queue size from frontend)

@stsquad is adding a new API in vhost-user to query that value. 

> 
> From the assumption, some vmm(crosvm) sends VHOST_USER_SET_VRING_NUM with maximum value(32768). So I was just curious if we can increase the queue size if there is no regression in QEMU.

Why using that value? It is really a big waste of resources to use such a big ring. What is the need?

I'm not in favor of using that large value hardwired into the device, but one thing we can do is make it parametric, so that you can run the daemon with a large value to run it with crosvm, while we keep the default at a reasonable value.

**Comment by stefano-garzarella** [comment]
This issue https://github.com/rust-vmm/vhost-device/issues/202 is proposing the same config option.

**Comment by ikicha** [comment]
Updates: crosvm has an option to set up queue size now.
