### ISSUE TITLE
Add a folder or nested workspace to support experimental devices

### ISSUE THREAD

**Issue by stefano-garzarella** [rust-vmm/vhost-device#459]
Some devices (such as virtio-gpu that we are discussing here: https://github.com/rust-vmm/vhost-device/pull/445) do not yet have a final specification merged into virtio-spec.

However, it would be useful to merge these devices anyway and maintain them until the specification is stable. For this reason we should provide a sub-directory (as suggested by @Ablu here: https://github.com/rust-vmm/vhost-device/pull/445#issuecomment-1736954474) or a nested workspace called for example `experimental` to support these devices.

**Comment by stefano-garzarella** [comment]
@Ablu mentioned that @epilys is working on RFC for this issue.

**Comment by epilys** [comment]
What we discussed in person is creating a `staging` workspace because of the following rationale:

- the name `experimental` implies they might not be functional (but if they are merged in this upstream repo, they should be working)
- `staging` as a nested workspace like @stefano-garzarella mentions in [#445](https://github.com/rust-vmm/vhost-device/pull/445#issuecomment-1737048637) has the benefit that when referring to the root workspace (e.g. `cargo check --all`, or `test` or `publish`) won't accidentally interact with non-vhost-upstreamed crates.

I will post a PR creating the workspace and explain its purpose and use in the README.

**Comment by stefano-garzarella** [comment]
> What we discussed in person is creating a `staging` workspace because of the following rationale:
> 
>     * the name `experimental` implies they might not be functional (but if they are merged in this upstream repo, they should be working)

Oh I see, yep I agree that `staging` is better and avoid confusion!

> 
>     * `staging` as a nested workspace like @stefano-garzarella mentions in [#445](https://github.com/rust-vmm/vhost-device/pull/445#issuecomment-1737048637) has the benefit that when referring to the root workspace (e.g. `cargo check --all`, or `test` or `publish`) won't accidentally interact with non-vhost-upstreamed crates.

I'm less worried about that, I mean we should always consider crates in staging for testing, etc.
But I agree that it's better to keep them separate from the main ones, and a nested workspace looks the best approach!

> 
> I will post a PR creating the workspace and explain its purpose and use in the README.

Thanks for that!
